# -*- coding: utf-8 -*-
"""Número primo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7R2KUTZPYq1k8xhRB6CmasTMZY5Zmqv
"""

num = int(input("Informe um valor natural: "))
cont = 0
d = 1
while d <= num:
  if num % d == 0 : cont = cont + 1
  d = d + 1
if cont == 2 : print(num, "É primo")
else: print(num, "Não é primo")