# -*- coding: utf-8 -*-
"""Peso Ideal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSpZkx-BYDSdkg7PvL9AFkWGlNDczWl6
"""

altura = float(input('Informe a altura: '))
genero = int(input('Informe o genero (use 1 para feminino e 2 para masculino:'))
if genero == 1 : peso = 62.1 * altura - 44.7
if genero == 2 : peso = 72.7 * altura - 58
print('Peso Ideal: ' , peso)