# -*- coding: utf-8 -*-
"""Quadrdado/cubo/quarta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKTsh9OZUcR2PIBvX2znrCOL3tz2in4W
"""

import math
print("Informe um valor: ")
valor = float(input())
print('Quadrado do valor: ' , valor ** 2)
print('Cubo do valor: ' , valor ** 3)
print('Valor na quarta: ' , valor ** 4)