# -*- coding: utf-8 -*-
"""raio/volume

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qdFJdVt4RGBXT449F2yuWZ3IdMt-BBC
"""

import math
print('Informe o valor do raio:')
raio = float(input())
volume = 4/3 * math.pi * math.pow(raio,3)
print('Volume: ' , volume)