# -*- coding: utf-8 -*-
"""Segundos, min, horas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEkIO_Pkq0Q89BiA7nqI2gPfCFW_VwBk
"""

print('Informe o tempo do evento em segundos: ')
tempo = int(input())
horas = tempo//3600
print('Horas: ' , horas)
resto = tempo%3600
minutos = resto//60
print('Minutos: ' , minutos)
segundos = resto % 60
print('Segundos: ' , segundos)