# -*- coding: utf-8 -*-
"""área esfera

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nD7Czusg2WnD4Ke0aFhDU9W8pH5vF1Jn
"""

import math
print('Informe o valor do raio: ')
raio = float(input())
area = 4 * math.pi * raio**2
print('área da esfera: ' , area)